### ISSUE TITLE
How to use the output jar file?

### ISSUE THREAD

**Issue by pb12121** [njiang8/Traffic_Model_NYC#1]
![4a37e7a40ed523e5c146a1a0bfd2b43](https://user-images.githubusercontent.com/56231094/183839648-609d6188-03ef-4e58-acbf-5d0a55004000.jpg)

**Comment by njiang8** [comment]
You can visit this link https://cs.gmu.edu/~eclab/projects/mason/extensions/geomason/GeoMasonOnEclipse.pdf and find step 3 under Section named "Run a GeoMason Example".

**Comment by pb12121** [comment]
Not running
![331a99f5b1680f2fbd7cb9ea544b56a](https://user-images.githubusercontent.com/56231094/185143564-6f0c6f48-08a4-412a-b2d8-4448edac1a71.jpg)
I follow the link https://cs.gmu.edu/~eclab/projects/mason/extensions/geomason/GeoMasonOnEclipse.pdf step by step, but my eclipse Compiling error. I saw your project and start learning Java, the understanding of Java is still relatively shallow, and Baidu has very little information on geomason, I hope you can give a hand. thanks a lot!

**Comment by njiang8** [comment]
If you want, you can email me at njiang8@gmu.edu, and I can set up a zoom meeting with you!
